<?xml version="1.0"?>
<Mukno>
	<Algorithm>
		<AlgNodes>
			<AlgNode>
				<Name>ImageReader</Name>
				<ID>0</ID>
				<Properties>
					<Alias />
					<DisplayType>Image3D</DisplayType>
					<Filename>filename-of-input-ct</Filename>
				</Properties>
				<AlgView>
					<Position>
						<X>-94.000000</X>
						<Y>-323.000000</Y>
					</Position>
				</AlgView>
			</AlgNode>
		</AlgNodes>
		<Edges />
	</Algorithm>
</Mukno>
